version: '2.0'

services:
  web:
    image: board.docker-registry.gewis.nl/wiso/web
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - database_volume:/code/db
    environment:
      SQLALCHEMY_DATABASE_URI: sqlite:///code/db/app.db
    expose:
    - 5000
    networks:
      - wiso
  nginx:
    image: board.docker-registry.gewis.nl/wiso/nginx
    ports:
      - 9601:80
    depends_on:
      - web
    networks:
      - wiso
volumes:
  database_volume:
networks:
  wiso:
    driver: bridge

