"""users and roles

Revision ID: 75c2ece7b3b5
Revises: 
Create Date: 2020-06-26 18:07:52.236200

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from app import user_manager
import os

# revision identifiers, used by Alembic.
revision = '75c2ece7b3b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role = op.create_table('role',
                           sa.Column('id', sa.Integer(), nullable=False),
                           sa.Column('name', sa.String(length=64), nullable=True),
                           sa.PrimaryKeyConstraint('id'),
                           sa.UniqueConstraint('name')
                           )
    user = op.create_table('user',
                           sa.Column('id', sa.Integer(), nullable=False),
                           sa.Column('username', sa.String(length=64), nullable=True),
                           sa.Column('password', sa.String(length=128), nullable=True),
                           sa.Column('email', sa.String(length=128), nullable=True),
                           sa.Column('association', sa.String(length=32), nullable=True),
                           sa.PrimaryKeyConstraint('id'),
                           sa.UniqueConstraint('email')
                           )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    user_roles = op.create_table('user_roles',
                                 sa.Column('id', sa.Integer(), nullable=False),
                                 sa.Column('user_id', sa.Integer(), nullable=True),
                                 sa.Column('role_id', sa.Integer(), nullable=True),
                                 sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
                                 sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                                 sa.PrimaryKeyConstraint('id')
                                 )
    # ### end Alembic commands ###

    # ### default data ###
    op.bulk_insert(role,
                   [
                       {'id': 1, 'name': 'Admin'},
                       {'id': 2, 'name': 'Organisator'},
                       {'id': 3, 'name': 'Voorzitter'},
                       {'id': 4, 'name': 'Bestuurslid'},
                       {'id': 5, 'name': 'Kandi'},

                   ])

    op.bulk_insert(user,
                   [{'id': 1,
                     'username': os.environ.get('WIMOS_ADMIN_USERNAME'),
                     'password': user_manager.password_manager.hash_password(os.environ.get('WIMOS_ADMIN_PASSWORD')),
                     'email': os.environ.get('WIMOS_ADMIN_EMAIL'),
                     'email_confirmed_at': datetime.now(),
                     'active': True,
                     'association': os.environ.get('WIMOS_ADMIN_ASSOCIATION')
                     }]
                   )
    op.bulk_insert(user_roles, [
        {'id': 1, 'user_id': 1, 'role_id': 1},
        {'id': 2, 'user_id': 1, 'role_id': 2},
        {'id': 3, 'user_id': 1, 'role_id': 3},
        {'id': 4, 'user_id': 1, 'role_id': 4}
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
