"""added email

Revision ID: 900e2c5b2d67
Revises: a6d5c000cdba
Create Date: 2020-11-22 12:35:59.183645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900e2c5b2d67'
down_revision = 'a6d5c000cdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed_at')
    # ### end Alembic commands ###
