"""alcoholstreep

Revision ID: e290d528e4be
Revises: 1066445071d6
Create Date: 2020-06-27 16:53:59.576271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e290d528e4be'
down_revision = '1066445071d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolution', sa.Column('alcohol', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resolution', 'alcohol')
    # ### end Alembic commands ###
